// Auto-generated by tools/gen_led_envelope.py — do not edit manually.
// RMS envelopes sampled every 50 ms from the breath WAV files.
//
// kLedEnvelopeIn  (ascending  0→255): cumulative-normalised RMS for inhalation.
//   Firmware applies gamma 2.2 for perceptual linearity. LED rises 0→peak.
//
// kLedEnvelopeOut (descending 255→0): sqrt-companded energy-remaining curve for exhalation.
//   brightness[i] = energy_remaining_before_window_i / total_energy.
//   Dims faster when audio is louder; guaranteed 255 at start, 0 at end.
//   Firmware uses directly (no inversion, no gamma). LED falls peak→0.
#pragma once
#include <stdint.h>

static const uint8_t kLedEnvelopeIn[80] = {
      0,   1,   1,   2,   2,   3,   3,   3,   4,   4,   5,   5,   6,   6,   7,   8,
      9,  10,  12,  13,  14,  16,  18,  20,  21,  23,  25,  27,  30,  33,  36,  39,
     42,  46,  50,  55,  60,  64,  70,  74,  79,  83,  89,  95, 101, 109, 115, 122,
    129, 138, 144, 150, 156, 162, 169, 175, 181, 187, 192, 198, 204, 210, 214, 218,
    221, 227, 231, 235, 238, 241, 243, 245, 247, 248, 250, 252, 253, 254, 254, 255
};

static const uint8_t kLedEnvelopeOut[120] = {
    255, 254, 252, 251, 250, 249, 247, 246, 245, 244, 243, 241, 240, 239, 238, 236,
    235, 234, 233, 232, 231, 229, 228, 227, 226, 225, 224, 223, 221, 220, 219, 218,
    217, 216, 215, 213, 212, 211, 210, 208, 206, 204, 201, 199, 196, 193, 191, 188,
    185, 182, 179, 176, 173, 170, 167, 164, 161, 157, 154, 151, 148, 144, 141, 137,
    134, 131, 127, 123, 119, 116, 112, 109, 105, 101,  98,  94,  91,  87,  84,  81,
     78,  75,  73,  70,  67,  64,  61,  58,  56,  53,  51,  48,  46,  43,  41,  39,
     37,  35,  33,  31,  29,  27,  25,  23,  21,  20,  18,  16,  15,  14,  12,  11,
      9,   8,   7,   6,   5,   3,   2,   0
};
