// Auto-generated by tools/gen_led_envelope.py — do not edit manually.
//
// Generation parameters:
//   on_db  = -40.0 dBFS (first-crossing — audio start)
//   off_db = -52.0 dBFS (last-crossing — audio fade-out)
//   profile bends = [0.00, 0.90, 1.50, 2.50]
//   breath_in : avg = -32.5 dBFS, peak = -24.4 dBFS,
//               active = [0.90s .. 3.95s]
//   breath_out: avg = -37.7 dBFS, peak = -29.6 dBFS,
//               active = [2.00s .. 5.95s]
//
// Both tables are sampled every 50 ms. Within the active region the
// curve is a linear-in-time ramp whose local slope is modulated by the
// audio's per-window dBFS relative to its own active-region average. The
// `bend` knob controls how strongly that modulation bends the linear base.
//
// kLedEnvelopeIn_i  (0 → 255): held at 0 before the first threshold crossing,
//                              ramps to 255 by the last crossing, then held at 255.
// kLedEnvelopeOut_i (255 → 0): held at 255 before the first threshold crossing,
//                              falls to 0 by the last crossing, then held at 0.
//
// Firmware indexes kLedEnvelope{In,Out}Profiles[currentBendIdx] at runtime.
#pragma once
#include <stdint.h>

#define LED_ENV_NUM_PROFILES 4
#define LED_ENV_WINDOW_MS   50
#define LED_ENV_IN_N        80
#define LED_ENV_OUT_N       120
#define BREATH_IN_MS        (LED_ENV_IN_N  * LED_ENV_WINDOW_MS)
#define BREATH_OUT_MS       (LED_ENV_OUT_N * LED_ENV_WINDOW_MS)

static const uint8_t kLedEnvelopeIn_0[80] = {
      0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   4,   8,  12,  16,  21,  25,  29,  33,  37,  41,  45,  49,  53,  58,
     62,  66,  70,  74,  78,  82,  86,  90,  95,  99, 103, 107, 111, 115, 119, 123,
    128, 132, 136, 140, 144, 148, 152, 156, 160, 165, 169, 173, 177, 181, 185, 189,
    193, 197, 202, 206, 210, 214, 218, 222, 226, 230, 234, 239, 243, 247, 251, 255
};

static const uint8_t kLedEnvelopeIn_1[80] = {
      0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   2,   4,   6,   8,  11,  13,  16,  18,  21,  23,  27,  30,  34,  37,
     41,  45,  49,  54,  59,  64,  70,  74,  79,  84,  89,  95, 101, 108, 114, 120,
    127, 134, 140, 145, 151, 157, 163, 169, 175, 180, 186, 191, 197, 203, 207, 212,
    216, 221, 226, 230, 233, 237, 240, 242, 245, 247, 249, 251, 253, 254, 254, 255
};

static const uint8_t kLedEnvelopeIn_2[80] = {
      0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   1,   1,   2,   4,   5,   7,   8,  10,  11,  13,  16,  19,  22,  25,
     29,  33,  37,  42,  48,  53,  59,  64,  70,  75,  80,  87,  94, 102, 109, 116,
    124, 133, 139, 146, 153, 160, 166, 173, 180, 186, 192, 199, 205, 212, 216, 221,
    225, 230, 236, 240, 242, 245, 248, 250, 251, 252, 253, 255, 255, 255, 255, 255
};

static const uint8_t kLedEnvelopeIn_3[80] = {
      0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   1,   1,   1,   2,   3,   4,   6,  10,  12,
     15,  19,  23,  28,  35,  40,  47,  51,  58,  63,  69,  77,  85,  94, 103, 111,
    120, 130, 138, 146, 153, 161, 169, 177, 185, 191, 198, 205, 212, 220, 224, 228,
    232, 239, 244, 248, 250, 252, 254, 255, 255, 255, 255, 255, 255, 255, 255, 255
};

static const uint8_t kLedEnvelopeOut_0[120] = {
    255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
    255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
    255, 255, 255, 255, 255, 255, 255, 255, 252, 249, 245, 242, 239, 236, 233, 230,
    226, 223, 220, 217, 214, 210, 207, 204, 201, 198, 194, 191, 188, 185, 182, 178,
    175, 172, 169, 166, 163, 159, 156, 153, 150, 147, 143, 140, 137, 134, 131, 128,
    124, 121, 118, 115, 112, 108, 105, 102,  99,  96,  92,  89,  86,  83,  80,  77,
     73,  70,  67,  64,  61,  57,  54,  51,  48,  45,  41,  38,  35,  32,  29,  25,
     22,  19,  16,  13,  10,   6,   3,   0
};

static const uint8_t kLedEnvelopeOut_1[120] = {
    255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
    255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
    255, 255, 255, 255, 255, 255, 255, 255, 252, 250, 246, 243, 240, 236, 233, 229,
    226, 222, 218, 214, 210, 206, 202, 198, 193, 189, 184, 180, 176, 171, 167, 162,
    157, 153, 147, 142, 138, 133, 128, 123, 118, 113, 108, 104,  99,  95,  91,  87,
     84,  80,  77,  74,  70,  66,  62,  59,  56,  53,  50,  47,  44,  42,  40,  37,
     35,  33,  30,  28,  26,  24,  21,  19,  17,  15,  14,  12,  11,  10,   9,   7,
      6,   5,   4,   3,   3,   1,   1,   0
};

static const uint8_t kLedEnvelopeOut_2[120] = {
    255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
    255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
    255, 255, 255, 255, 255, 255, 255, 255, 253, 250, 247, 243, 240, 237, 233, 229,
    226, 222, 217, 213, 209, 204, 200, 195, 190, 186, 180, 175, 170, 165, 160, 154,
    149, 143, 137, 131, 126, 120, 115, 109, 103,  97,  92,  86,  81,  76,  72,  68,
     64,  61,  57,  54,  50,  46,  42,  38,  35,  32,  30,  27,  25,  23,  21,  19,
     17,  15,  14,  12,  10,   9,   7,   5,   4,   3,   2,   1,   1,   1,   1,   0,
      0,   0,   0,   0,   0,   0,   0,   0
};

static const uint8_t kLedEnvelopeOut_3[120] = {
    255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
    255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
    255, 255, 255, 255, 255, 255, 255, 255, 253, 251, 248, 245, 242, 238, 235, 231,
    228, 223, 219, 214, 210, 205, 200, 195, 190, 185, 178, 173, 168, 162, 156, 150,
    144, 138, 131, 124, 119, 112, 106,  99,  92,  86,  79,  74,  68,  62,  58,  54,
     50,  47,  44,  41,  36,  32,  28,  25,  21,  19,  17,  14,  13,  12,  10,   9,
      8,   7,   6,   5,   4,   3,   2,   1,   1,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0
};

static const uint8_t *const kLedEnvelopeInProfiles[LED_ENV_NUM_PROFILES] = {
    kLedEnvelopeIn_0, kLedEnvelopeIn_1, kLedEnvelopeIn_2, kLedEnvelopeIn_3
};

static const uint8_t *const kLedEnvelopeOutProfiles[LED_ENV_NUM_PROFILES] = {
    kLedEnvelopeOut_0, kLedEnvelopeOut_1, kLedEnvelopeOut_2, kLedEnvelopeOut_3
};

static const char *const kLedEnvelopeProfileLabels[LED_ENV_NUM_PROFILES] = {
    "0.00", "0.90", "1.50", "2.50"
};
