#!/usr/bin/env python3
"""
gen_led_envelope.py
Analyses breath_in.wav and breath_out.wav and writes include/led_envelope.h
with pre-computed RMS amplitude envelopes for use by the ESP32 LED driver.

Usage:
    python3 tools/gen_led_envelope.py
"""

import wave
import struct
import math
import os

# 50 ms windows at 16 kHz = 800 samples per window
SAMPLE_RATE    = 16000
WINDOW_MS      = 50
WINDOW_SAMPLES = SAMPLE_RATE * WINDOW_MS // 1000  # 800

SCRIPT_DIR  = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT   = os.path.dirname(SCRIPT_DIR)
AUDIO_DIR   = os.path.join(REPO_ROOT, "audio")
INCLUDE_DIR = os.path.join(REPO_ROOT, "include")


def rms_envelope(path: str) -> list[float]:
    """Return list of RMS values (one per 50 ms window) from a mono 16-bit WAV."""
    with wave.open(path, "rb") as wf:
        assert wf.getsampwidth() == 2, "Expected 16-bit samples"
        assert wf.getnchannels() == 1, "Expected mono audio"
        assert wf.getframerate() == SAMPLE_RATE, f"Expected {SAMPLE_RATE} Hz"
        raw = wf.readframes(wf.getnframes())

    # Unpack to signed 16-bit integers
    samples = struct.unpack(f"<{len(raw)//2}h", raw)

    envelope = []
    for i in range(0, len(samples), WINDOW_SAMPLES):
        window = samples[i : i + WINDOW_SAMPLES]
        if not window:
            break
        rms = math.sqrt(sum(s * s for s in window) / len(window))
        envelope.append(rms)

    return envelope


def cumsum_normalise(values: list[float]) -> list[int]:
    """Cumulative sum of RMS values, normalised so the final value = 255.

    The result is a monotonically non-decreasing easing curve: a loud window
    makes the sum jump quickly (LED changes fast at that moment); a quiet window
    makes it advance slowly (LED changes slowly).  Used for breath_in (0→255).
    """
    cs: list[float] = []
    total = 0.0
    for v in values:
        total += v
        cs.append(total)
    peak = cs[-1] if cs else 1.0
    return [round(v / peak * 255) for v in cs]


def cumsum_descending(values: list[float]) -> list[int]:
    """Descending brightness curve for exhalation (255 → 0).

    sqrt companding is applied first to reduce dynamic range (e.g. 18:1 → 4:1),
    giving a more even distribution of LED change across the phase.

    brightness[i] = energy_remaining_before_window_i / total_energy × 255

    This means:
    - The LED dims faster when the audio is louder (more energy spent per window)
    - The LED dims slower when the audio is quieter
    - First value is always 255 (full brightness at start of exhalation)
    - Last  value is always 0   (LED off exactly at end of exhalation)

    Firmware uses this array directly (no inversion, no gamma) for breath_out.
    """
    compressed = [math.sqrt(v) for v in values]
    total = sum(compressed)
    if total == 0:
        return [0] * len(values)
    running = 0.0
    result = []
    for v in compressed:
        result.append(round((1.0 - running / total) * 255))
        running += v
    result[0]  = 255  # guarantee exact start
    result[-1] = 0    # guarantee exact end
    return result


def format_array(name: str, data: list[int]) -> str:
    items_per_line = 16
    lines = []
    for i in range(0, len(data), items_per_line):
        chunk = data[i : i + items_per_line]
        lines.append("    " + ", ".join(f"{v:3d}" for v in chunk))
    body = ",\n".join(lines)
    return f"static const uint8_t {name}[{len(data)}] = {{\n{body}\n}};"


def main():
    env_in_raw  = rms_envelope(os.path.join(AUDIO_DIR, "breath_in.wav"))
    env_out_raw = rms_envelope(os.path.join(AUDIO_DIR, "breath_out.wav"))

    env_in  = cumsum_normalise(env_in_raw)
    env_out = cumsum_descending(env_out_raw)

    print(f"breath_in  : {len(env_in)} windows, "
          f"peak_rms={max(env_in_raw):.1f}, first_uint8={env_in[0]} (should be 0), "
          f"final_uint8={env_in[-1]} (should be 255)")
    print(f"breath_out : {len(env_out)} windows, "
          f"peak_rms={max(env_out_raw):.1f}, first_uint8={env_out[0]} (should be 255), "
          f"final_uint8={env_out[-1]} (should be 0)")

    header = f"""\
// Auto-generated by tools/gen_led_envelope.py — do not edit manually.
// RMS envelopes sampled every {WINDOW_MS} ms from the breath WAV files.
//
// kLedEnvelopeIn  (ascending  0→255): cumulative-normalised RMS for inhalation.
//   Firmware applies gamma 2.2 for perceptual linearity. LED rises 0→peak.
//
// kLedEnvelopeOut (descending 255→0): sqrt-companded energy-remaining curve for exhalation.
//   brightness[i] = energy_remaining_before_window_i / total_energy.
//   Dims faster when audio is louder; guaranteed 255 at start, 0 at end.
//   Firmware uses directly (no inversion, no gamma). LED falls peak→0.
#pragma once
#include <stdint.h>

{format_array("kLedEnvelopeIn", env_in)}

{format_array("kLedEnvelopeOut", env_out)}
"""

    out_path = os.path.join(INCLUDE_DIR, "led_envelope.h")
    with open(out_path, "w") as f:
        f.write(header)
    print(f"Wrote {out_path}")


if __name__ == "__main__":
    main()
